### ISSUE TITLE
Name openretractions.com not resolved

### ISSUE THREAD

**Issue by dbcliu** [fathomlabs/open-retractions#18]
When using a script calling the api of open retractions, I find that the name is not resolved anymore. I have to add the name into the host file to make it work again. Maybe it shall be fixed.

**Comment by chartgerink** [comment]
Thanks @dbcliu for reporting this issue!

@blahah did the registration expire? We never did migrate this domain 😅

**Comment by blahah** [comment]
The registration continues until 2023, but my email was temporarily unavailable so Google domains stopped serving the DNS! Fixed now - thanks for reporting @dbcliu 🙏
